export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpg",
        username: "Isuru Sajith",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpg",
        username: "Saminda Ruwan",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpg",
        username: "Kavindi Samarakoon",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpg",
        username: "Nimesha Nishadi",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpg",
        username: "Nawan Perera",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpg",
        username: "Naveen Avishka",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpg",
        username: "Elsy Perry",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpg",
        username: "Upul Sampath"
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpg",
        username: "Dasun Gairika",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpg",
        username: "Pavithra Dias",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love For All, Hatred For None.",
        photo: "assets/post/1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/post/2.jpg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Not in the periphery but in the core",
        photo: "assets/post/3.jpg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "assets/post/4.jpg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "assets/post/5.jpg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "assets/post/6.jpg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "No regrets No surrender",
        photo: "assets/post/7.jpg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        desc: "Visit Sri Lanka!",
        photo: "assets/post/8.jpg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "I Love I wanna love cuz Love is gender free",
        photo: "assets/post/9.jpg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        desc: "Freedom",
        photo: "assets/post/10.jpg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];